services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 80:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: test
  #     PGADMIN_DEFAULT_PASSWORD: test